/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppWord {
        "weight": number;
    }
    interface SctButton {
    }
    interface SctWordcloud {
        /**
          * The words to be displayed in the word cloud
         */
        "words": string[];
    }
}
declare global {
    interface HTMLAppWordElement extends Components.AppWord, HTMLStencilElement {
    }
    var HTMLAppWordElement: {
        prototype: HTMLAppWordElement;
        new (): HTMLAppWordElement;
    };
    interface HTMLSctButtonElement extends Components.SctButton, HTMLStencilElement {
    }
    var HTMLSctButtonElement: {
        prototype: HTMLSctButtonElement;
        new (): HTMLSctButtonElement;
    };
    interface HTMLSctWordcloudElement extends Components.SctWordcloud, HTMLStencilElement {
    }
    var HTMLSctWordcloudElement: {
        prototype: HTMLSctWordcloudElement;
        new (): HTMLSctWordcloudElement;
    };
    interface HTMLElementTagNameMap {
        "app-word": HTMLAppWordElement;
        "sct-button": HTMLSctButtonElement;
        "sct-wordcloud": HTMLSctWordcloudElement;
    }
}
declare namespace LocalJSX {
    interface AppWord {
        "weight": number;
    }
    interface SctButton {
    }
    interface SctWordcloud {
        /**
          * The words to be displayed in the word cloud
         */
        "words": string[];
    }
    interface IntrinsicElements {
        "app-word": AppWord;
        "sct-button": SctButton;
        "sct-wordcloud": SctWordcloud;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-word": LocalJSX.AppWord & JSXBase.HTMLAttributes<HTMLAppWordElement>;
            "sct-button": LocalJSX.SctButton & JSXBase.HTMLAttributes<HTMLSctButtonElement>;
            "sct-wordcloud": LocalJSX.SctWordcloud & JSXBase.HTMLAttributes<HTMLSctWordcloudElement>;
        }
    }
}
